Finalize create-config script

diff --git a/config/create-config b/config/create-config
--- a/config/create-config
+++ b/config/create-config
@@ -10,10 +10,10 @@ usage() {
     echo "--shared-secret <shared secret>"
     echo "--api-domain-name <API domain name>"
     echo "--api-domain-certificate-name <API domain certificate name>"
-    echo "--route53-region <Route 53 - Region>"
-    echo "--route53-zone-id <Route 53 - Zone ID>"
-    echo "--route53-record-ttl <Route 53 - Record TTL>"
-    echo "--route53-record-type <Route 53 - Record Type>"
+    echo "--route53-region <Route53 - Region>"
+    echo "--route53-zone-id <Route53 - Zone ID>"
+    echo "--route53-record-ttl <Route53 - Record TTL>"
+    echo "--route53-record-type <Route53 - Record Type>"
     echo "--s3-region <S3 - Region>"
     echo "--s3-bucket <S3 - Bucket>"
     echo "--s3-key <S3 - Key>" 
@@ -21,7 +21,28 @@ usage() {
     exit
 }
 
-#type grep   >/dev/null 2>&1 || { echo >&2 "I require 'grep' but it's not installed. Aborting."; exit 1; }
+replace-tokens() {
+    FILE=$1
+    replace "@@URL@@" "$URL" $FILE
+    replace "@@DNS_HOSTNAME@@" "$DNS_HOSTNAME" $FILE
+    replace "@@SHARED_SECRET@@" "$SHARED_SECRET" $FILE
+    replace "@@API_DOMAIN_NAME@@" "$API_DOMAIN_NAME" $FILE
+    replace "@@API_DOMAIN_CERTIFICATE_NAME@@" "$API_DOMAIN_CERTIFICATE_NAME" $FILE
+    replace "@@ROUTE53_REGION@@" "$ROUTE53_REGION" $FILE
+    replace "@@ROUTE53_ZONE_ID@@" "$ROUTE53_ZONE_ID" $FILE
+    replace "@@ROUTE53_RECORD_TTL@@" "$ROUTE53_RECORD_TTL" $FILE
+    replace "@@ROUTE53_RECORD_TYPE@@" "$ROUTE53_RECORD_TYPE" $FILE
+    replace "@@S3_REGION@@" "$S3_REGION" $FILE
+    replace "@@S3_BUCKET@@" "$S3_BUCKET" $FILE
+    replace "@@S3_KEY@@" "$S3_KEY" $FILE
+} 
+
+function replace {
+  sed -i "s/$(echo $1 | sed -e 's/\([[\/.*]\|\]\)/\\&/g')/$(echo $2 | sed -e 's/[\/&]/\\&/g')/g" $3
+}
+
+type read   >/dev/null 2>&1 || { echo >&2 "I require 'read' but it's not installed. Aborting."; exit 1; }
+type sed    >/dev/null 2>&1 || { echo >&2 "I require 'sed' but it's not installed. Aborting."; exit 1; }
 
 SILENT=no
 while [ "$1" != "" ]; do
@@ -45,16 +66,16 @@ while [ "$1" != "" ]; do
                                         API_DOMAIN_CERTIFICATE_NAME=$1
                                         ;;
         --route53-region )              shift
-                                        ROUTE_53_REGION=$1
+                                        ROUTE53_REGION=$1
                                         ;;
         --route53-zone-id )             shift
-                                        ROUTE_53_ZONE_ID=$1
+                                        ROUTE53_ZONE_ID=$1
                                         ;;
         --route53-record-ttl )          shift
-                                        ROUTE_53_RECORD_TTL=$1
+                                        ROUTE53_RECORD_TTL=$1
                                         ;;
         --route53-record-type )         shift
-                                        ROUTE_53_RECORD_TYPE=$1
+                                        ROUTE53_RECORD_TYPE=$1
                                         ;;
         --s3-region )                   shift
                                         S3_REGION=$1
@@ -79,10 +100,10 @@ if [ "$SILENT" == "no" ]; then
     read -p "Shared Secret                  : " SHARED_SECRET
     read -p "API Domain - Name              : " API_DOMAIN_NAME
     read -p "API Domain - Certificate Name  : " API_DOMAIN_CERTIFICATE_NAME
-    read -p "Route 53 - Region              : " ROUTE_53_REGION
-    read -p "Route 53 - Zone ID             : " ROUTE_53_ZONE_ID
-    read -p "Route 53 - Record TTL          : " ROUTE_53_RECORD_TTL
-    read -p "Route 53 - Record Type         : " ROUTE_53_RECORD_TYPE
+    read -p "Route53 - Region               : " ROUTE53_REGION
+    read -p "Route53 - Zone ID              : " ROUTE53_ZONE_ID
+    read -p "Route53 - Record TTL           : " ROUTE53_RECORD_TTL
+    read -p "Route53 - Record Type          : " ROUTE53_RECORD_TYPE
     read -p "S3 - Region                    : " S3_REGION
     read -p "S3 - Bucket                    : " S3_BUCKET
     read -p "S3 - Key                       : " S3_KEY
@@ -93,50 +114,23 @@ fi
 [ -z $SHARED_SECRET ] && usage
 [ -z $API_DOMAIN_NAME ] && usage
 [ -z $API_DOMAIN_CERTIFICATE_NAME ] && usage
-[ -z $ROUTE_53_REGION ] && usage
-[ -z $ROUTE_53_ZONE_ID ] && usage
-[ -z $ROUTE_53_RECORD_TTL ] && usage
-[ -z $ROUTE_53_RECORD_TYPE ] && usage
+[ -z $ROUTE53_REGION ] && usage
+[ -z $ROUTE53_ZONE_ID ] && usage
+[ -z $ROUTE53_RECORD_TTL ] && usage
+[ -z $ROUTE53_RECORD_TYPE ] && usage
 [ -z $S3_REGION ] && usage
 [ -z $S3_BUCKET ] && usage
 [ -z $S3_KEY ] && usage
 
 URL=https://$API_DOMAIN_NAME
 
-echo "Data"
-echo "===="
-echo $SILENT
-echo $STAGE
-echo $DNS_HOSTNAME
-echo $SHARED_SECRET
-echo $API_DOMAIN_NAME
-echo $API_DOMAIN_CERTIFICATE_NAME
-echo $ROUTE_53_REGION
-echo $ROUTE_53_ZONE_ID
-echo $ROUTE_53_RECORD_TTL
-echo $ROUTE_53_RECORD_TYPE
-echo $S3_REGION
-echo $S3_BUCKET
-echo $S3_KEY
-
 BASEDIR=$(dirname "$0")
+
 cp $BASEDIR/server.config.template $BASEDIR/server-$STAGE.config
+replace-tokens $BASEDIR/server-$STAGE.config
+
 cp $BASEDIR/serverless.config.template $BASEDIR/serverless-$STAGE.config
+replace-tokens $BASEDIR/serverless-$STAGE.config
+
 cp $BASEDIR/client.config.template $BASEDIR/client-$STAGE.config
-
-
-
-exit 0
-
-SILENT
-DNS_HOSTNAME
-SHARED_SECRET
-API_DOMAIN_NAME
-API_DOMAIN_CERTIFICATE_NAME
-ROUTE_53_REGION
-ROUTE_53_ZONE_ID
-ROUTE_53_RECORD_TTL
-ROUTE_53_RECORD_TYPE
-S3_REGION
-S3_BUCKET
-S3_KEY
+replace-tokens $BASEDIR/client-$STAGE.config
